@extends('layouts.app')
@section('title', $product->product_name)
@section('content')
<div class="back-link"><a href="{{ route('market-watch.index') }}">← Market Watch</a></div>
<div class="page-heading"><div><div class="eyebrow">PRODUCT DETAIL · {{ $product->external_product_id ?? 'MANUAL' }}</div><h1>{{ $product->product_name }}</h1><p>{{ $product->category ?? 'Uncategorized' }} · {{ $product->shop_name ?? 'Unknown shop' }}</p></div><a class="button secondary" href="{{ route('products.edit', $product) }}">Edit product</a></div>
<div class="detail-grid"><div>
<section class="panel image-panel">@if($product->main_image)<img class="hero-image" src="{{ asset($product->main_image->local_path) }}" alt="Mock image for {{ $product->product_name }}">@else<div class="image-empty">No product image available</div>@endif
<div class="gallery">@foreach($product->images as $image)<a href="{{ route('products.images.download', [$product, $image]) }}" title="Download image"><img src="{{ asset($image->local_path) }}" alt="{{ $image->image_type }} image"></a>@endforeach</div>
<div class="actions">@if($product->main_image)<a class="button secondary" href="{{ route('products.images.download', [$product, $product->main_image]) }}">Download main image</a><a class="button secondary" href="{{ route('products.images.download-all', $product) }}">Download all images</a>@else<span class="muted">Downloads available when local images are attached.</span>@endif</div></section>
<section class="panel"><div class="section-heading"><h2>Content matrix</h2><a href="{{ route('contents.create', ['product_id' => $product->id]) }}">Create content →</a></div><div class="table-scroll"><table><thead><tr><th>Page</th><th>Image</th><th>AI video</th><th>Real</th></tr></thead><tbody>@foreach($pages as $page)<tr><td>{{ $page->name }}</td>@foreach(['image_post','ai_video','real_review'] as $type)@php $match = $product->contents->first(fn($item) => $item->page_id === $page->id && $item->content_type === $type); @endphp<td>@if($match)<span class="badge good">{{ $match->status }}</span>@else<span class="muted">—</span>@endif</td>@endforeach</tr>@endforeach</tbody></table></div></section>
</div><div>
<section class="panel"><div class="section-heading"><h2>Opportunity</h2><span class="score large {{ $product->score_status }}">{{ $product->opportunity_score ?? '—' }}</span></div><div class="info-grid"><span>EXTRA COMM</span><strong>{{ $product->has_extra_comm ? 'Yes · eligible' : 'No · excluded from main list' }}</strong><span>Status</span><strong>{{ str_replace('_', ' ', $product->product_status->value) }}</strong><span>Base commission</span><strong>{{ $product->base_commission === null ? '—' : $product->base_commission.'%' }}</strong><span>Extra commission</span><strong>{{ $product->extra_commission === null ? '—' : $product->extra_commission.'%' }}</strong></div>@unless($product->has_extra_comm)<p class="notice">This product is not a main opportunity because EXTRA COMM is absent.</p>@endunless</section>
<section class="panel"><h2>Product facts</h2><div class="info-grid"><span>Price</span><strong>{{ $product->price === null ? '—' : '฿'.number_format((float)$product->price, 2) }}</strong><span>Sale price</span><strong>{{ $product->sale_price === null ? '—' : '฿'.number_format((float)$product->sale_price, 2) }}</strong><span>Rating</span><strong>{{ $product->rating ?? '—' }}</strong><span>Reviews</span><strong>{{ $product->review_count === null ? '—' : number_format($product->review_count) }}</strong><span>Sold</span><strong>{{ $product->sold_count === null ? '—' : number_format($product->sold_count) }}</strong></div></section>
<section class="panel"><h2>Links & actions</h2><div class="link-box"><small>PRODUCT URL</small><div>{{ $product->product_url ?? 'No product URL' }}</div></div><div class="link-box"><small>AFFILIATE URL</small><div>{{ $product->affiliate_url ?? 'No affiliate URL' }}</div></div><div class="actions">@if($product->product_url)<a class="button secondary" href="{{ $product->product_url }}" target="_blank" rel="noopener noreferrer">Open product ↗</a>@endif @if($product->affiliate_url)<button class="button primary" type="button" data-copy-link="{{ $product->affiliate_url }}" data-log-url="{{ route('products.affiliate-copy', $product) }}">Copy affiliate link</button>@else<span class="muted">No link to copy.</span>@endif</div><p class="inline-feedback" id="copy-feedback" role="status"></p></section>
<section class="panel"><h2>Data freshness</h2><div class="info-grid"><span>Product checked</span><strong>{{ $product->last_checked_at?->format('d M Y H:i') ?? 'Not checked' }}</strong><span>EXTRA COMM</span><strong>{{ $product->extra_comm_checked_at?->format('d M Y H:i') ?? 'Not checked' }}</strong><span>Affiliate link</span><strong>{{ $product->affiliate_link_checked_at?->format('d M Y H:i') ?? 'Not checked' }}</strong><span>Images</span><strong>{{ $product->images_checked_at?->format('d M Y H:i') ?? 'Not checked' }}</strong></div></section>
</div></div>
<section class="panel"><div class="section-heading"><h2>Snapshots</h2><span class="muted">Historical mock data</span></div><div class="table-scroll"><table><thead><tr><th>Date</th><th>Price</th><th>Sold</th><th>Reviews</th><th>EXTRA COMM</th></tr></thead><tbody>@forelse($product->snapshots as $snapshot)<tr><td>{{ $snapshot->snapshot_date->format('d M Y') }}</td><td>{{ $snapshot->sale_price ?? '—' }}</td><td>{{ $snapshot->sold_count ?? '—' }}</td><td>{{ $snapshot->review_count ?? '—' }}</td><td>{{ $snapshot->has_extra_comm ? 'Yes' : 'No' }}</td></tr>@empty<tr><td colspan="5" class="empty">No snapshots yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
